import type { Finding, PipelineEvent, WorkflowEdge, WorkflowNode } from '@/types'

const base = 1_785_326_400

const node = (offset: number, workflowNode: WorkflowNode): PipelineEvent => ({
  timestamp: base + offset,
  type: 'workflow_node',
  workflow_node: workflowNode,
})

const edge = (offset: number, workflowEdge: WorkflowEdge): PipelineEvent => ({
  timestamp: base + offset,
  type: 'workflow_edge',
  workflow_edge: workflowEdge,
})

const criticalFinding: Finding = {
  id: 'demo-critical',
  category: 'security',
  severity: 'critical',
  confidence: 0.91,
  file: 'src/auth/session.py',
  line_start: 57,
  line_end: 61,
  title: '已撤销的刷新令牌仍可签发新会话',
  reasoning: '新的快速路径只验证签名，跳过了旧实现使用的撤销列表查询。',
  trigger_path: 'POST /session/refresh -> refresh_session -> issue_access_token',
  suggestion: '签发凭据前，使用令牌标识查询撤销存储。',
}

const rejectedFinding: Finding = {
  id: 'demo-rejected',
  category: 'static',
  severity: 'medium',
  confidence: 0.64,
  file: 'tests/test_session.py',
  line_start: 88,
  line_end: 88,
  title: '测试辅助函数使用固定令牌标识',
  reasoning: '固定标识可能在并行测试之间共享状态。',
  trigger_path: 'parallel test execution',
  suggestion: '为每个测试生成唯一标识。',
}

export const demoEvents: PipelineEvent[] = [
  node(0, {
    id: 'input',
    kind: 'input',
    label: '解析 PR 变更',
    status: 'running',
    detail: '读取 diff 并建立代码上下文。',
  }),
  node(0.2, {
    id: 'coordinator',
    kind: 'coordinator',
    label: 'Coordinator 动态规划',
    status: 'running',
    agent: 'coordinator',
    task_id: 'coordinator',
    detail: '分析改动面、风险信号与可并行边界。',
  }),
  edge(0.25, {
    id: 'input-coordinator',
    source: 'input',
    target: 'coordinator',
    relation: 'dispatch',
  }),
  node(0.4, {
    id: 'input',
    kind: 'input',
    label: '解析 PR 变更',
    status: 'completed',
    detail: '已生成 2 个上下文包，命中认证与测试代码。',
  }),
  {
    timestamp: base + 0.55,
    type: 'thought',
    agent: 'coordinator',
    task_id: 'coordinator',
    text: '认证路径属于高风险边界；安全、业务意图和调用链可以并行检查。',
  },
  node(0.7, {
    id: 'task-security',
    kind: 'agent_task',
    label: '检查令牌撤销与凭据签发边界',
    status: 'queued',
    agent: 'defect',
    task_id: 'task-security',
    detail: '优先级 96 · 安全专家',
  }),
  edge(0.72, {
    id: 'dispatch-security',
    source: 'coordinator',
    target: 'task-security',
    relation: 'dispatch',
  }),
  node(0.84, {
    id: 'task-intent',
    kind: 'agent_task',
    label: '核对刷新会话的业务不变量',
    status: 'queued',
    agent: 'intent',
    task_id: 'task-intent',
    detail: '优先级 88 · 意图专家',
  }),
  edge(0.86, {
    id: 'dispatch-intent',
    source: 'coordinator',
    target: 'task-intent',
    relation: 'dispatch',
  }),
  node(0.98, {
    id: 'task-callers',
    kind: 'agent_task',
    label: '追踪刷新接口的调用与保护链',
    status: 'queued',
    agent: 'defect',
    task_id: 'task-callers',
    detail: '优先级 82 · 独立调用链检查',
  }),
  edge(1, {
    id: 'dispatch-callers',
    source: 'coordinator',
    target: 'task-callers',
    relation: 'dispatch',
  }),
  node(1.12, {
    id: 'coordinator',
    kind: 'coordinator',
    label: 'Coordinator 动态规划',
    status: 'completed',
    agent: 'coordinator',
    task_id: 'coordinator',
    detail: '拆解为 3 个无依赖任务，允许同时执行。',
  }),
  node(1.25, {
    id: 'task-security',
    kind: 'agent_task',
    label: '检查令牌撤销与凭据签发边界',
    status: 'running',
    agent: 'defect',
    task_id: 'task-security',
    detail: '正在检查安全边界。',
  }),
  node(1.32, {
    id: 'task-intent',
    kind: 'agent_task',
    label: '核对刷新会话的业务不变量',
    status: 'running',
    agent: 'intent',
    task_id: 'task-intent',
    detail: '正在还原 PR 意图。',
  }),
  node(1.39, {
    id: 'task-callers',
    kind: 'agent_task',
    label: '追踪刷新接口的调用与保护链',
    status: 'running',
    agent: 'defect',
    task_id: 'task-callers',
    detail: '正在搜索调用者与上游保护。',
  }),
  {
    timestamp: base + 1.55,
    type: 'tool',
    agent: 'defect',
    task_id: 'task-security',
    tool: 'read_file',
    args: { path: 'src/auth/session.py', start: 38, end: 86 },
  },
  node(1.57, {
    id: 'tool-security-read',
    kind: 'tool',
    label: '读取会话实现',
    status: 'completed',
    task_id: 'task-security',
    detail: 'src/auth/session.py:38-86',
  }),
  edge(1.59, {
    id: 'security-tool-call',
    source: 'task-security',
    target: 'tool-security-read',
    relation: 'tool_call',
  }),
  edge(1.61, {
    id: 'security-tool-evidence',
    source: 'tool-security-read',
    target: 'task-security',
    relation: 'evidence',
  }),
  {
    timestamp: base + 1.78,
    type: 'tool',
    agent: 'intent',
    task_id: 'task-intent',
    tool: 'git_blame',
    args: { path: 'src/auth/session.py', start: 52, end: 64 },
  },
  node(1.8, {
    id: 'tool-intent-blame',
    kind: 'tool',
    label: '查询历史语义',
    status: 'completed',
    task_id: 'task-intent',
    detail: '确认撤销检查是既有安全不变量。',
  }),
  edge(1.82, {
    id: 'intent-tool-call',
    source: 'task-intent',
    target: 'tool-intent-blame',
    relation: 'tool_call',
  }),
  {
    timestamp: base + 2,
    type: 'tool',
    agent: 'defect',
    task_id: 'task-callers',
    tool: 'get_callers',
    args: { function: 'refresh_session' },
  },
  node(2.02, {
    id: 'tool-callers',
    kind: 'tool',
    label: '搜索接口调用者',
    status: 'completed',
    task_id: 'task-callers',
    detail: '发现 POST /session/refresh 可直接到达。',
  }),
  edge(2.04, {
    id: 'callers-tool-call',
    source: 'task-callers',
    target: 'tool-callers',
    relation: 'tool_call',
  }),
  {
    timestamp: base + 2.2,
    type: 'thought',
    agent: 'intent',
    task_id: 'task-intent',
    text: 'PR 只要求降低刷新延迟，没有授权移除撤销校验。',
  },
  node(2.4, {
    id: 'task-intent',
    kind: 'agent_task',
    label: '核对刷新会话的业务不变量',
    status: 'completed',
    agent: 'intent',
    task_id: 'task-intent',
    detail: '确认撤销校验属于不可移除的业务约束。',
  }),
  node(2.5, {
    id: 'task-callers',
    kind: 'agent_task',
    label: '追踪刷新接口的调用与保护链',
    status: 'completed',
    agent: 'defect',
    task_id: 'task-callers',
    detail: '确认生产路由可达，且上游没有等价保护。',
  }),
  node(2.62, {
    id: 'finding-demo-critical',
    kind: 'finding',
    label: criticalFinding.title,
    status: 'waiting',
    detail: 'src/auth/session.py:57 · critical',
  }),
  edge(2.64, {
    id: 'candidate-critical',
    source: 'task-security',
    target: 'finding-demo-critical',
    relation: 'candidate',
  }),
  { timestamp: base + 2.66, type: 'finding', finding: criticalFinding },
  node(2.78, {
    id: 'finding-demo-rejected',
    kind: 'finding',
    label: rejectedFinding.title,
    status: 'waiting',
    detail: 'tests/test_session.py:88 · medium',
  }),
  edge(2.8, {
    id: 'candidate-rejected',
    source: 'task-security',
    target: 'finding-demo-rejected',
    relation: 'candidate',
  }),
  { timestamp: base + 2.82, type: 'finding', finding: rejectedFinding },
  node(2.95, {
    id: 'task-security',
    kind: 'agent_task',
    label: '检查令牌撤销与凭据签发边界',
    status: 'completed',
    agent: 'defect',
    task_id: 'task-security',
    detail: '提交 2 条候选问题，其中 1 条为 critical。',
  }),
  node(3.08, {
    id: 'cross-check-4',
    kind: 'agent_task',
    label: '从意图视角独立复核高风险结论',
    status: 'queued',
    agent: 'intent',
    task_id: 'cross-check-4',
    detail: 'Coordinator 根据 critical Finding 动态追加。',
  }),
  edge(3.1, {
    id: 'handoff-security-cross',
    source: 'task-security',
    target: 'cross-check-4',
    relation: 'handoff',
  }),
  node(3.25, {
    id: 'cross-check-4',
    kind: 'agent_task',
    label: '从意图视角独立复核高风险结论',
    status: 'running',
    agent: 'intent',
    task_id: 'cross-check-4',
    detail: '使用独立上下文质疑安全专家结论。',
  }),
  {
    timestamp: base + 3.42,
    type: 'thought',
    agent: 'intent',
    task_id: 'cross-check-4',
    text: '撤销令牌仍能经过生产路由签发凭据，原结论与业务不变量一致。',
  },
  node(3.58, {
    id: 'cross-check-4',
    kind: 'agent_task',
    label: '从意图视角独立复核高风险结论',
    status: 'completed',
    agent: 'intent',
    task_id: 'cross-check-4',
    detail: '交叉验证通过，保留候选进入 Verifier。',
  }),
  node(3.72, {
    id: 'verify-demo-critical',
    kind: 'verifier',
    label: '质疑：已撤销令牌仍可签发新会话',
    status: 'queued',
    agent: 'verifier',
    task_id: 'verify-demo-critical',
  }),
  edge(3.74, {
    id: 'challenge-critical',
    source: 'finding-demo-critical',
    target: 'verify-demo-critical',
    relation: 'challenge',
  }),
  node(3.84, {
    id: 'verify-demo-rejected',
    kind: 'verifier',
    label: '质疑：测试辅助函数使用固定令牌标识',
    status: 'queued',
    agent: 'verifier',
    task_id: 'verify-demo-rejected',
  }),
  edge(3.86, {
    id: 'challenge-rejected',
    source: 'finding-demo-rejected',
    target: 'verify-demo-rejected',
    relation: 'challenge',
  }),
  node(4, {
    id: 'verify-demo-critical',
    kind: 'verifier',
    label: '质疑：已撤销令牌仍可签发新会话',
    status: 'running',
    agent: 'verifier',
    task_id: 'verify-demo-critical',
  }),
  node(4.06, {
    id: 'verify-demo-rejected',
    kind: 'verifier',
    label: '质疑：测试辅助函数使用固定令牌标识',
    status: 'running',
    agent: 'verifier',
    task_id: 'verify-demo-rejected',
  }),
  {
    timestamp: base + 4.3,
    type: 'verdict',
    task_id: 'verify-demo-rejected',
    verdict: {
      finding_id: 'demo-rejected',
      verdict: 'reject',
      reason: '该位置仅属于测试代码，不影响生产行为。',
      confidence_adjusted: 0.2,
    },
  },
  node(4.32, {
    id: 'verify-demo-rejected',
    kind: 'verifier',
    label: '质疑：测试辅助函数使用固定令牌标识',
    status: 'completed',
    agent: 'verifier',
    task_id: 'verify-demo-rejected',
    detail: '驳回：无法到达生产路径。',
  }),
  node(4.34, {
    id: 'finding-demo-rejected',
    kind: 'finding',
    label: rejectedFinding.title,
    status: 'cancelled',
    detail: 'Verifier 已驳回。',
  }),
  edge(4.36, {
    id: 'result-rejected',
    source: 'verify-demo-rejected',
    target: 'finding-demo-rejected',
    relation: 'result',
  }),
  {
    timestamp: base + 4.55,
    type: 'verdict',
    task_id: 'verify-demo-critical',
    verdict: {
      finding_id: 'demo-critical',
      verdict: 'keep',
      reason: '刷新路由可达，且上游不存在等价的撤销保护。',
      confidence_adjusted: 0.94,
    },
  },
  node(4.57, {
    id: 'verify-demo-critical',
    kind: 'verifier',
    label: '质疑：已撤销令牌仍可签发新会话',
    status: 'completed',
    agent: 'verifier',
    task_id: 'verify-demo-critical',
    detail: '保留：证据、可达性与影响均成立。',
  }),
  node(4.59, {
    id: 'finding-demo-critical',
    kind: 'finding',
    label: criticalFinding.title,
    status: 'completed',
    detail: 'Verifier 已确认，置信度 94%。',
  }),
  edge(4.61, {
    id: 'result-critical',
    source: 'verify-demo-critical',
    target: 'finding-demo-critical',
    relation: 'result',
  }),
  node(4.8, {
    id: 'report',
    kind: 'report',
    label: '汇总审查报告',
    status: 'running',
    detail: '合并通过验证的 Finding。',
  }),
  edge(4.82, {
    id: 'critical-report',
    source: 'finding-demo-critical',
    target: 'report',
    relation: 'result',
  }),
  node(5, {
    id: 'report',
    kind: 'report',
    label: '汇总审查报告',
    status: 'completed',
    detail: '保留 1 条 critical Finding，驳回 1 条误报。',
  }),
  {
    timestamp: base + 5.05,
    type: 'report',
    markdown: '# 审查摘要\n\n保留 1 条严重问题，已由独立 Verifier 完成证据复核。',
  },
]

export const demoDiff = `diff --git a/src/auth/session.py b/src/auth/session.py
--- a/src/auth/session.py
+++ b/src/auth/session.py
@@ -54,9 +54,8 @@ async def refresh_session(token: str):
     payload = verify_signature(token)
-    if await revoked_tokens.contains(payload.jti):
-        raise InvalidToken("revoked")
+    # Signature verification is enough for the fast path.
     session = await issue_access_token(payload.subject)
     return session
`
